"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-*xvm^lf2nsg7x4sw!oik61dk_4=!uy$z_cguhl0@o=-)ttq9v9')

"""ENV-настройки
DJANGO_ENV=production  -> продакшен режим
DJANGO_ENV=local       -> локальный режим (по умолчанию)
"""
DJANGO_ENV = os.getenv('DJANGO_ENV', 'local').lower()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '1' if DJANGO_ENV == 'local' else '0') == '1'

# Allowed hosts configuration
# In production, MUST set DJANGO_ALLOWED_HOSTS in .env
# For Nginx Proxy Manager, include both IP and domain
default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '172.30.4.14',  # ZeroTier IP
]
env_allowed_hosts = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS = env_allowed_hosts if env_allowed_hosts else default_allowed_hosts


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'donations',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ДОБАВИТЬ для статических файлов
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DJANGO_ENV == 'local':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # MySQL (Beget)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DATABASE', ''),
            'USER': os.getenv('MYSQL_USER', ''),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', ''),
            'HOST': os.getenv('MYSQL_HOST', 'localhost'),
            'PORT': os.getenv('MYSQL_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'ru-ru'  # ИЗМЕНИТЬ на русский

TIME_ZONE = 'Europe/Moscow'  # ИЗМЕНИТЬ на московское время

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Beget будет искать здесь статику

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Папка со статическими файлами
]

# ДОБАВИТЬ для WhiteNoise (сжатие статики)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (если будут загрузки пользователей)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS configuration
# For Nginx Proxy Manager: allow requests from proxy domains
default_cors = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://172.30.4.14",
    "http://172.30.4.14:8001",
]
if DJANGO_ENV == 'local':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    env_cors = [h.strip() for h in os.getenv('DJANGO_CORS_ORIGINS', '').split(',') if h.strip()]
    CORS_ALLOWED_ORIGINS = env_cors if env_cors else default_cors

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF configuration
# For Nginx Proxy Manager with SSL: include https:// origins
default_csrf = [
    'http://localhost',
    'http://127.0.0.1',
    'http://172.30.4.14',
    'http://172.30.4.14:8001',
]
env_csrf = [h.strip() for h in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = env_csrf if env_csrf else default_csrf

# Trust X-Forwarded-Proto header from Nginx Proxy Manager
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security settings for production
if DJANGO_ENV != 'local':
    # Uncomment when using HTTPS via Nginx Proxy Manager
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    pass

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
